/*
* generated by Xtext
*/
package net.certware.argument.language.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import net.certware.argument.language.services.LGrammarAccess;

public class LParser extends AbstractContentAssistParser {
	
	@Inject
	private LGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected net.certware.argument.language.ui.contentassist.antlr.internal.InternalLParser createParser() {
		net.certware.argument.language.ui.contentassist.antlr.internal.InternalLParser result = new net.certware.argument.language.ui.contentassist.antlr.internal.InternalLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getBasicTermAccess().getAlternatives(), "rule__BasicTerm__Alternatives");
					put(grammarAccess.getAdditionAccess().getAlternatives_1_1(), "rule__Addition__Alternatives_1_1");
					put(grammarAccess.getMultiplicationAccess().getAlternatives_1_1(), "rule__Multiplication__Alternatives_1_1");
					put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
					put(grammarAccess.getArithmeticLiteralAccess().getAlternatives(), "rule__ArithmeticLiteral__Alternatives");
					put(grammarAccess.getSetMultiplicationAccess().getAlternatives_1_1(), "rule__SetMultiplication__Alternatives_1_1");
					put(grammarAccess.getSetPrimaryAccess().getAlternatives(), "rule__SetPrimary__Alternatives");
					put(grammarAccess.getSetLiteralAccess().getValueAlternatives_0(), "rule__SetLiteral__ValueAlternatives_0");
					put(grammarAccess.getQuantifierAccess().getAlternatives(), "rule__Quantifier__Alternatives");
					put(grammarAccess.getTermAccess().getAlternatives(), "rule__Term__Alternatives");
					put(grammarAccess.getAtomAccess().getAlternatives(), "rule__Atom__Alternatives");
					put(grammarAccess.getAtomOpAccess().getAlternatives(), "rule__AtomOp__Alternatives");
					put(grammarAccess.getNotSentenceAccess().getAlternatives(), "rule__NotSentence__Alternatives");
					put(grammarAccess.getPrimarySentenceAccess().getAlternatives(), "rule__PrimarySentence__Alternatives");
					put(grammarAccess.getHeadAccess().getAlternatives(), "rule__Head__Alternatives");
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getTypedVariableAccess().getGroup(), "rule__TypedVariable__Group__0");
					put(grammarAccess.getAdditionAccess().getGroup(), "rule__Addition__Group__0");
					put(grammarAccess.getAdditionAccess().getGroup_1(), "rule__Addition__Group_1__0");
					put(grammarAccess.getMultiplicationAccess().getGroup(), "rule__Multiplication__Group__0");
					put(grammarAccess.getMultiplicationAccess().getGroup_1(), "rule__Multiplication__Group_1__0");
					put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
					put(grammarAccess.getFunctionalTermAccess().getGroup(), "rule__FunctionalTerm__Group__0");
					put(grammarAccess.getBasicTermsAccess().getGroup(), "rule__BasicTerms__Group__0");
					put(grammarAccess.getBasicTermsAccess().getGroup_1(), "rule__BasicTerms__Group_1__0");
					put(grammarAccess.getConstantDeclarationAccess().getGroup(), "rule__ConstantDeclaration__Group__0");
					put(grammarAccess.getTypeDeclarationAccess().getGroup(), "rule__TypeDeclaration__Group__0");
					put(grammarAccess.getSetAccess().getGroup(), "rule__Set__Group__0");
					put(grammarAccess.getRangeAccess().getGroup(), "rule__Range__Group__0");
					put(grammarAccess.getSetConstructAccess().getGroup(), "rule__SetConstruct__Group__0");
					put(grammarAccess.getTVarsAccess().getGroup(), "rule__TVars__Group__0");
					put(grammarAccess.getTVarsAccess().getGroup_1(), "rule__TVars__Group_1__0");
					put(grammarAccess.getTVarAccess().getGroup(), "rule__TVar__Group__0");
					put(grammarAccess.getSetAdditionAccess().getGroup(), "rule__SetAddition__Group__0");
					put(grammarAccess.getSetAdditionAccess().getGroup_1(), "rule__SetAddition__Group_1__0");
					put(grammarAccess.getSetMultiplicationAccess().getGroup(), "rule__SetMultiplication__Group__0");
					put(grammarAccess.getSetMultiplicationAccess().getGroup_1(), "rule__SetMultiplication__Group_1__0");
					put(grammarAccess.getSetPrimaryAccess().getGroup_1(), "rule__SetPrimary__Group_1__0");
					put(grammarAccess.getQuantifiedTermAccess().getGroup(), "rule__QuantifiedTerm__Group__0");
					put(grammarAccess.getPredicateAtomAccess().getGroup(), "rule__PredicateAtom__Group__0");
					put(grammarAccess.getPredicateAtomAccess().getGroup_1(), "rule__PredicateAtom__Group_1__0");
					put(grammarAccess.getBuiltInAtomAccess().getGroup(), "rule__BuiltInAtom__Group__0");
					put(grammarAccess.getOrSentenceAccess().getGroup(), "rule__OrSentence__Group__0");
					put(grammarAccess.getOrSentenceAccess().getGroup_1(), "rule__OrSentence__Group_1__0");
					put(grammarAccess.getAndSentenceAccess().getGroup(), "rule__AndSentence__Group__0");
					put(grammarAccess.getAndSentenceAccess().getGroup_1(), "rule__AndSentence__Group_1__0");
					put(grammarAccess.getNotSentenceAccess().getGroup_1(), "rule__NotSentence__Group_1__0");
					put(grammarAccess.getPrimarySentenceAccess().getGroup_1(), "rule__PrimarySentence__Group_1__0");
					put(grammarAccess.getMaybeLiteralAccess().getGroup(), "rule__MaybeLiteral__Group__0");
					put(grammarAccess.getCardinalityConstraintAccess().getGroup(), "rule__CardinalityConstraint__Group__0");
					put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
					put(grammarAccess.getRuleAccess().getGroup_1(), "rule__Rule__Group_1__0");
					put(grammarAccess.getProgramAccess().getStatementsAssignment(), "rule__Program__StatementsAssignment");
					put(grammarAccess.getNumericConstantAccess().getValueAssignment(), "rule__NumericConstant__ValueAssignment");
					put(grammarAccess.getVariableAccess().getIdentifierAssignment(), "rule__Variable__IdentifierAssignment");
					put(grammarAccess.getTypedVariableAccess().getTypeAssignment_0(), "rule__TypedVariable__TypeAssignment_0");
					put(grammarAccess.getTypedVariableAccess().getVarAssignment_1(), "rule__TypedVariable__VarAssignment_1");
					put(grammarAccess.getAdditionAccess().getRhsAssignment_1_2(), "rule__Addition__RhsAssignment_1_2");
					put(grammarAccess.getMultiplicationAccess().getRhsAssignment_1_2(), "rule__Multiplication__RhsAssignment_1_2");
					put(grammarAccess.getArithmeticLiteralAccess().getIdentifierAssignment_0(), "rule__ArithmeticLiteral__IdentifierAssignment_0");
					put(grammarAccess.getArithmeticLiteralAccess().getValueAssignment_1(), "rule__ArithmeticLiteral__ValueAssignment_1");
					put(grammarAccess.getBasicTermsAccess().getCarAssignment_0(), "rule__BasicTerms__CarAssignment_0");
					put(grammarAccess.getBasicTermsAccess().getCdrAssignment_1_1(), "rule__BasicTerms__CdrAssignment_1_1");
					put(grammarAccess.getConstantDeclarationAccess().getIdAssignment_0(), "rule__ConstantDeclaration__IdAssignment_0");
					put(grammarAccess.getConstantDeclarationAccess().getCvAssignment_2(), "rule__ConstantDeclaration__CvAssignment_2");
					put(grammarAccess.getTypeDeclarationAccess().getIdAssignment_0(), "rule__TypeDeclaration__IdAssignment_0");
					put(grammarAccess.getTypeDeclarationAccess().getExpAssignment_2(), "rule__TypeDeclaration__ExpAssignment_2");
					put(grammarAccess.getLimitAccess().getCvAssignment(), "rule__Limit__CvAssignment");
					put(grammarAccess.getSetAccess().getLhsAssignment_0(), "rule__Set__LhsAssignment_0");
					put(grammarAccess.getSetAccess().getTermsAssignment_1(), "rule__Set__TermsAssignment_1");
					put(grammarAccess.getRangeAccess().getLhsAssignment_1(), "rule__Range__LhsAssignment_1");
					put(grammarAccess.getRangeAccess().getRhsAssignment_4(), "rule__Range__RhsAssignment_4");
					put(grammarAccess.getSetConstructAccess().getLhsAssignment_0(), "rule__SetConstruct__LhsAssignment_0");
					put(grammarAccess.getSetConstructAccess().getRhsAssignment_2(), "rule__SetConstruct__RhsAssignment_2");
					put(grammarAccess.getTVarsAccess().getCarAssignment_0(), "rule__TVars__CarAssignment_0");
					put(grammarAccess.getTVarsAccess().getCdrAssignment_1_1(), "rule__TVars__CdrAssignment_1_1");
					put(grammarAccess.getSetAdditionAccess().getRightAssignment_1_2(), "rule__SetAddition__RightAssignment_1_2");
					put(grammarAccess.getSetMultiplicationAccess().getRightAssignment_1_2(), "rule__SetMultiplication__RightAssignment_1_2");
					put(grammarAccess.getSetLiteralAccess().getValueAssignment(), "rule__SetLiteral__ValueAssignment");
					put(grammarAccess.getPredicateAtomAccess().getFidAssignment_0(), "rule__PredicateAtom__FidAssignment_0");
					put(grammarAccess.getPredicateAtomAccess().getTermsAssignment_1_1(), "rule__PredicateAtom__TermsAssignment_1_1");
					put(grammarAccess.getBuiltInAtomAccess().getLhsAssignment_0(), "rule__BuiltInAtom__LhsAssignment_0");
					put(grammarAccess.getBuiltInAtomAccess().getOpAssignment_1(), "rule__BuiltInAtom__OpAssignment_1");
					put(grammarAccess.getBuiltInAtomAccess().getRhsAssignment_2(), "rule__BuiltInAtom__RhsAssignment_2");
					put(grammarAccess.getOrSentenceAccess().getRightAssignment_1_2(), "rule__OrSentence__RightAssignment_1_2");
					put(grammarAccess.getAndSentenceAccess().getRightAssignment_1_2(), "rule__AndSentence__RightAssignment_1_2");
					put(grammarAccess.getCardinalityConstraintAccess().getLhsAssignment_0(), "rule__CardinalityConstraint__LhsAssignment_0");
					put(grammarAccess.getCardinalityConstraintAccess().getIdAssignment_4(), "rule__CardinalityConstraint__IdAssignment_4");
					put(grammarAccess.getCardinalityConstraintAccess().getTermsAssignment_6(), "rule__CardinalityConstraint__TermsAssignment_6");
					put(grammarAccess.getCardinalityConstraintAccess().getRhsAssignment_11(), "rule__CardinalityConstraint__RhsAssignment_11");
					put(grammarAccess.getBoundAccess().getAvAssignment(), "rule__Bound__AvAssignment");
					put(grammarAccess.getRuleAccess().getHeadAssignment_0(), "rule__Rule__HeadAssignment_0");
					put(grammarAccess.getRuleAccess().getBodyAssignment_1_1(), "rule__Rule__BodyAssignment_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			net.certware.argument.language.ui.contentassist.antlr.internal.InternalLParser typedParser = (net.certware.argument.language.ui.contentassist.antlr.internal.InternalLParser) parser;
			typedParser.entryRuleProgram();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public LGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
