/**
 * generated by Xtext
 */
package net.certware.argument.language.ui.contentassist;

import net.certware.argument.language.ui.contentassist.AbstractLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class LProposalProvider extends AbstractLProposalProvider {
}
