/*
 * generated by Xtext
 */
package net.certware.argument.language.ui.contentassist

import net.certware.argument.language.ui.contentassist.AbstractLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class LProposalProvider extends AbstractLProposalProvider {
}
