/**
 * generated by Xtext
 */
package net.certware.argument.language.validation;

import net.certware.argument.language.validation.AbstractLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class LValidator extends AbstractLValidator {
}
