/*
 * generated by Xtext
 */
package net.certware.argument.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LUiModule extends net.certware.argument.language.ui.AbstractLUiModule {
	public LUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
